### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by srrathi**

### CODE REVIEW

**Review by thealphadollar — APPROVED** [review]
Thank you for your contributions. This is small, though a valid and important update 🎉

**Comment by srrathi** [comment]
Can you please label my pull request as 'hacktoberfest-accepted' if possible.

**Comment by thealphadollar** [comment]
@srrathi Sure, done. Just a small suggestion; please try to improve the quality of contributions as time passes, although PRs are always welcome - I generally do not accept a PR (for hacktoberfest) that just adds a single and has no implication on the project as such. I'm genuinely thankful for your understanding, and I'm hoping you will be contributing in meaningful ways to open source.

**Comment by srrathi** [comment]
yes sir now I'll try to make better PR with some valid commits.
Thank you

**Pull request merged**
